"""empty message

Revision ID: c49f3c4fae77
Revises: d7bf91c3282e
Create Date: 2022-11-24 10:42:14.493141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c49f3c4fae77'
down_revision = 'd7bf91c3282e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('character', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('character', 'hair_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'skin_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'eye_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'birth_year',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'homeworld',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'species',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'vehicles',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'starships',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('character', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'episode_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('films', 'opening_crawl',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'director',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'producer',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'release_date',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'characters',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'planets',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'starships',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'vehicles',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'species',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('films', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'terrain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('planet', 'residents',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('planet', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'classification',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'designation',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'average_height',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('species', 'skin_colors',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'hair_colors',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'eye_colors',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'average_lifespan',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('species', 'homeworld',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'language',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'people',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('species', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'model',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'starship_class',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'manufacturer',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'cost_in_credits',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'length',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'crew',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'max_atmosphering_speed',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'hyperdrive_rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'mglt',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'cargo_capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('starship', 'consumables',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'pilots',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('starship', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('thread', 'message',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'model',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'vehicle_class',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'manufacturer',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'cost_in_credits',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'length',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'crew',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'max_atmosphering_speed',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'cargo_capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('vehicle', 'consumables',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'pilots',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('vehicle', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'pilots',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'consumables',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'cargo_capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'max_atmosphering_speed',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'crew',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'length',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'cost_in_credits',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('vehicle', 'manufacturer',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'vehicle_class',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('vehicle', 'model',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('thread', 'message',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'pilots',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'consumables',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'cargo_capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'mglt',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'hyperdrive_rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'max_atmosphering_speed',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'passengers',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'crew',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'length',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'cost_in_credits',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('starship', 'manufacturer',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'starship_class',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('starship', 'model',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'people',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'language',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'homeworld',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'average_lifespan',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('species', 'eye_colors',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'hair_colors',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'skin_colors',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'average_height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('species', 'designation',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('species', 'classification',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'residents',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'population',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'surface_water',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'terrain',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'climate',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('planet', 'diameter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'orbital_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('planet', 'rotation_period',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('films', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'species',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'vehicles',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'starships',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'planets',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'characters',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'release_date',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'producer',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'director',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'opening_crawl',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('films', 'episode_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('character', 'url',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'edited',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'created',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'starships',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'vehicles',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'species',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'films',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'homeworld',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'gender',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'birth_year',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'eye_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'skin_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'hair_color',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    op.alter_column('character', 'mass',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('character', 'height',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
